name: Ubuntu Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Upgrade pip and pre-cache requirements
        run: |
          python -m pip install --upgrade pip
          echo "Pre-caching requirements to create cache folder"
          pip install --dry-run --ignore-installed -r requirements.txt

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-cache-v4-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-cache-v4-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install JMeter
        run: |
          sudo apt-get update
          sudo apt-get install -y jmeter

      - name: Start API server in background
        run: |
          nohup python3 src/api.py &

      - name: Wait for server to start
        run: sleep 5

      - name: Test connection to Flask
        run: curl http://127.0.0.1:5000/

      - name: Run API tests
        run: pytest tests/test_api.py -v

      - name: Run Usuarios tests
        run: pytest tests/test_usuarios.py -v

      - name: Run regression tests
        run: pytest tests/test_regresion_pytest.py -v

      - name: Run JMeter performance test and generate report
        run: |
          jmeter -n -t tests/Test_rendimiento_plataforma_peso.jmx -l tests/results.jtl -e -o tests/html-report

      - name: Upload JMeter HTML report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-report
          path: tests/html-report
