name: Test Plataforma Peso

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            pip-${{ runner.os }}-

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: playwright-browsers-${{ runner.os }}-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            playwright-browsers-${{ runner.os }}-

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright pytest-playwright

      - name: Install Playwright browsers (skip if cached)
        run: |
          playwright install --with-deps chromium

      - name: Start Flask server (background)
        run: |
          cd src
          nohup python api.py > flask.log 2>&1 &
          
          # Esperar a que el servidor arranque
          for i in {1..10}; do
            if curl -s http://localhost:5000 > /dev/null; then
              echo "Servidor Flask iniciado"
              break
            fi
            echo "Esperando servidor Flask..."
            sleep 2
          done

          if ! curl -s http://localhost:5000 > /dev/null; then
            echo "El servidor Flask no se inició a tiempo"
            exit 1
          fi

      - name: Run tests
        run: python tests/test_funcionales_selenium.py
        env:
          FLASK_URL: "http://localhost:5000"

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-resultado
          path: screenshot.png
