name: Test Plataforma Peso

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Cache Playwright browsers
        uses: actions/cache@v3
        with:
          path: C:/Users/runneradmin/AppData/Local/ms-playwright
          key: playwright-browsers-${{ runner.os }}-v1
          restore-keys: |
            playwright-browsers-${{ runner.os }}-

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install playwright pytest-playwright

      - name: Install Playwright browsers (skip if cached)
        run: |
          playwright install --with-deps chromium

      - name: Start Flask server (background)
        run: |
          $job = Start-Job -ScriptBlock {
            cd src
            python api.py
          }

          $maxRetries = 10
          $retry = 0
          while ($retry -lt $maxRetries) {
            try {
              curl http://localhost:5000 > $null
              break
            } catch {
              Start-Sleep -Seconds 2
              $retry++
            }
          }

          if ($retry -eq $maxRetries) {
            Write-Error "Flask server failed to start in time"
            Exit 1
          }
        shell: pwsh

      - name: Run tests
        run: python tests/test_funcionales_selenium.py
        env:
          FLASK_URL: "http://localhost:5000"

      - name: Upload screenshot
        uses: actions/upload-artifact@v4
        with:
          name: screenshot-resultado
          path: screenshot.png
