name: Windows Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Upgrade pip and create cache dir
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade pip
          echo "Pre-caching requirements to create cache folder"
          pip install --dry-run --ignore-installed -r requirements.txt
        shell: cmd

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: C:\Users\runneradmin\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-cache-v4-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-cache-v4-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Start API server in background
        run: start /b python src/api.py
        shell: cmd

      - name: Wait for server to start
        run: ping -n 6 127.0.0.1 > nul
        shell: cmd

      - name: Run API tests
        run: pytest .\tests\test_api.py -v

      - name: Run Usuarios tests
        run: pytest .\tests\test_usuarios.py -v

      - name: Run regresion tests
        run: pytest .\tests\test_regresion_pytest.py -v

      - name: Install JMeter
        run: choco install jmeter -y
        shell: cmd

      - name: Run JMeter performance test
        run: jmeter -n -t tests\Test_rendimiento_plataforma_peso.jmx -l tests\results.jtl
        shell: cmd
